name: special-offers-development
networks:
  special-offers:
    driver: bridge

volumes:
  storage_data:

services:
  database:
    image: postgres:15
    container_name: special-offers-db
    env_file: .env
    environment:
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD}
      - POSTGRES_DB=${PGSQL_DATABASE}
    ports:
      - ${PGSQL_PORT}:5432
    networks:
      - 'special-offers'
